INSERT INTO products (name, description, price, stock_qty, low_stock_threshold, category_id, is_active, created_at, updated_at)
VALUES
('Alaska Evaporated Milk 370ml', 'Evap milk', 28.00, 80, 20, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Alaska Condensed Milk', 'Sweetened milk', 35.00, 70, 15, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Bear Brand Milk 300ml', 'Fortified milk', 25.00, 100, 25, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Nido 3+ Powder', 'Milk powder for kids', 120.00, 40, 10, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Magnolia Fresh Milk 1L', 'Fresh milk', 95.00, 30, 8, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Nestle Cream', 'All purpose cream', 32.00, 60, 15, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Yogurt Strawberry', 'Fruit yogurt', 20.00, 50, 10, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Yogurt Plain', 'Plain yogurt', 18.00, 45, 10, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Cheddar Cheese Slice', 'Processed cheese', 65.00, 40, 10, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Mozzarella Cheese Block', 'Pizza cheese', 120.00, 25, 5, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Butter Cup 225g', 'Creamy butter', 90.00, 30, 8, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Cream Cheese Spread', 'Soft cheese spread', 75.00, 20, 5, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Chocolate Milk Drink', 'Flavored milk', 22.00, 80, 20, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Milk Powder Sachet', 'Single serve milk', 15.00, 100, 25, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Fresh Cream 250ml', 'Whipping cream', 88.00, 20, 5, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('UHT Milk 1L', 'Long life milk', 85.00, 40, 10, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Powdered Milk Full Cream', 'Milk powder', 150.00, 35, 10, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW()),
('Evap Milk Small', 'Small can evaporated milk', 18.00, 90, 20, (SELECT id FROM categories WHERE name='Dairy'), TRUE, NOW(), NOW());

INSERT INTO products (name, description, price, stock_qty, low_stock_threshold, category_id, is_active, created_at, updated_at)
VALUES
('Frozen Chicken 1kg', 'Whole chicken frozen', 180.00, 30, 8, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Hotdog Pack', 'Processed hotdog', 120.00, 40, 10, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Meatballs', 'Beef meatballs', 150.00, 25, 5, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Fish Fillet', 'Basa fish fillet', 160.00, 20, 5, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Squid Rings', 'Calamari rings', 200.00, 15, 5, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Fries 1kg', 'French fries', 130.00, 50, 15, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Nuggets', 'Chicken nuggets', 140.00, 45, 10, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Burger Patty', 'Beef patties', 160.00, 35, 10, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Lumpia', 'Spring rolls', 110.00, 60, 15, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Fish Ball', 'Street food fish balls', 90.00, 80, 20, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Siomai', 'Pork siomai', 120.00, 70, 15, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Tofu', 'Soft tofu', 60.00, 40, 10, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Beef Slice', 'Shabu-shabu beef', 250.00, 20, 5, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Pork Belly', 'Samgyeopsal cut', 220.00, 25, 5, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Ice Cream Tub', 'Vanilla ice cream', 180.00, 30, 8, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Pizza', 'Ready to cook pizza', 200.00, 20, 5, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW()),
('Frozen Corn', 'Sweet corn kernels', 70.00, 60, 15, (SELECT id FROM categories WHERE name='Frozen Foods'), TRUE, NOW(), NOW());

INSERT INTO products (name, description, price, stock_qty, low_stock_threshold, category_id, is_active, created_at, updated_at)
VALUES
('Silver Swan Soy Sauce', 'Classic soy sauce', 25.00, 100, 20, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Datu Puti Vinegar', 'Cane vinegar', 22.00, 90, 20, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Banana Ketchup', 'Sweet ketchup', 30.00, 80, 15, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Tomato Ketchup', 'Classic ketchup', 35.00, 70, 15, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Oyster Sauce', 'Cooking sauce', 45.00, 60, 10, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Fish Sauce', 'Patis seasoning', 28.00, 90, 20, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Mayonnaise Jar', 'Creamy mayo', 55.00, 50, 10, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Hot Sauce Bottle', 'Chili sauce', 40.00, 60, 10, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Garlic Powder', 'Seasoning powder', 35.00, 40, 10, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Onion Powder', 'Seasoning powder', 35.00, 40, 10, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Black Pepper Ground', 'Pepper spice', 50.00, 50, 10, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Salt Refined', 'Table salt', 20.00, 120, 30, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Soy Sauce Light', 'Light soy sauce', 30.00, 80, 15, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Sweet Chili Sauce', 'Dip sauce', 45.00, 60, 10, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW()),
('Barbecue Sauce', 'BBQ sauce', 60.00, 40, 10, (SELECT id FROM categories WHERE name='Condiments'), TRUE, NOW(), NOW());

INSERT INTO products (name, description, price, stock_qty, low_stock_threshold, category_id, is_active, created_at, updated_at)
VALUES
('Canola Oil 1L', 'Cooking oil', 120.00, 40, 10, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Palm Oil 1L', 'Cooking oil', 90.00, 50, 10, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Coconut Oil', 'Virgin coconut oil', 150.00, 30, 8, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('White Sugar 1kg', 'Refined sugar', 60.00, 100, 20, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Brown Sugar', 'Raw sugar', 65.00, 90, 20, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('All Purpose Flour', 'Baking flour', 70.00, 80, 15, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Cornstarch', 'Thickener', 40.00, 60, 10, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Vinegar Large Bottle', 'Cooking vinegar', 35.00, 90, 20, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Soy Sauce Large', 'Big bottle soy sauce', 45.00, 70, 15, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Cooking Wine', 'For cooking', 80.00, 30, 5, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Chicken Cubes', 'Bouillon cubes', 25.00, 120, 30, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Pork Cubes', 'Bouillon cubes', 25.00, 120, 30, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Beef Cubes', 'Bouillon cubes', 25.00, 120, 30, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Instant Sauce Mix', 'Gravy mix', 30.00, 80, 20, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Cooking Salt Pack', 'Refined salt', 20.00, 150, 40, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Garlic Whole', 'Fresh garlic', 10.00, 200, 50, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Onion Red', 'Fresh onion', 12.00, 180, 50, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Ginger Fresh', 'Fresh ginger', 15.00, 150, 40, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Cooking Oil Small', 'Small bottle oil', 55.00, 90, 20, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW()),
('Seasoning Mix', 'All-purpose seasoning', 35.00, 70, 15, (SELECT id FROM categories WHERE name='Cooking Essentials'), TRUE, NOW(), NOW());

INSERT INTO products (name, description, price, stock_qty, low_stock_threshold, category_id, is_active, created_at, updated_at)
VALUES
('Safeguard Soap', 'Antibacterial soap', 35.00, 120, 30, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Dove Soap', 'Beauty soap', 45.00, 90, 20, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Shampoo Sachet', 'Single shampoo pack', 8.00, 200, 50, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Head & Shoulders Shampoo', 'Anti-dandruff shampoo', 120.00, 50, 10, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Toothpaste Small', 'Travel size toothpaste', 20.00, 150, 40, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Colgate Toothpaste', 'Fluoride toothpaste', 75.00, 80, 20, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Toothbrush Soft', 'Soft bristle brush', 25.00, 120, 30, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Rexona Deodorant', 'Deodorant spray', 90.00, 60, 15, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Alcohol 70%', 'Disinfectant', 45.00, 100, 25, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Face Mask Pack', 'Disposable mask', 30.00, 150, 40, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Cotton Buds', 'Ear cleaning buds', 20.00, 100, 30, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Facial Wash', 'Skin cleanser', 80.00, 70, 20, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Body Lotion', 'Skin moisturizer', 110.00, 60, 15, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Razor Blade Pack', 'Shaving blades', 50.00, 80, 20, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Feminine Wash', 'Hygiene wash', 95.00, 40, 10, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Sanitary Pads', 'Feminine pads', 60.00, 90, 20, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Hand Sanitizer', 'Alcohol gel', 55.00, 120, 30, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Baby Oil', 'Baby care oil', 70.00, 60, 15, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Shaving Cream', 'Shave foam', 85.00, 40, 10, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW()),
('Perfume Small', 'Pocket perfume', 120.00, 30, 8, (SELECT id FROM categories WHERE name='Personal Care'), TRUE, NOW(), NOW());